services:
  anonim-web:
    build:
      context: .
      args:
        DJANGO_ENV: prod
    env_file:
      - .env.prod
    expose:
      - "8000"
    volumes:
      - /srv/data_anonin:/data     # хостовая папка с БД
      - /srv/media_anonin:/app/media
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
