services:
  anonim-web:
    container_name: anonim-web
    build:
      context: .
      args:
        DJANGO_ENV: prod
    env_file:
      - .env.prod
    expose:
      - "8000"
    volumes:
      - /srv/data_anonim:/data
      - /srv/media_anonim:/app/media
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
