# Generated by Django 5.2.5 on 2025-09-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_user_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditablePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'О проекте'), ('faq', 'FAQ'), ('contacts', 'Полезные контакты'), ('what_to_do', 'Что делать, если...')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
