# Generated by Django 5.2.5 on 2025-09-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_editablepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat ID для уведомлений', max_length=64, null=True),
        ),
    ]
