# Generated by Django 5.2.5 on 2025-09-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='unique_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
