# Generated by Django 5.2.5 on 2025-09-02 06:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_school_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablepage',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызский')], default='ru', max_length=2),
        ),
        migrations.AlterField(
            model_name='editablepage',
            name='page',
            field=models.CharField(choices=[('about', 'О проекте'), ('faq', 'FAQ'), ('contacts', 'Полезные контакты'), ('what_to_do', 'Что делать, если...')], max_length=32),
        ),
        migrations.AlterField(
            model_name='school',
            name='unique_code',
            field=models.CharField(blank=True, default=core.models.generate_unique_code, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='editablepage',
            unique_together={('page', 'language')},
        ),
    ]
