# Generated by Django 5.2.5 on 2025-09-03 11:01

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_editablepage_language_alter_editablepage_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editablepage',
            options={'verbose_name': 'Редактируемая страница', 'verbose_name_plural': 'Редактируемые страницы'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='editablepage',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='editablepage',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызский')], default='ru', max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='editablepage',
            name='page',
            field=models.CharField(choices=[('about', 'О проекте'), ('faq', 'FAQ'), ('contacts', 'Полезные контакты'), ('what_to_do', 'Что делать, если...'), ('instructions', 'Инструкции'), ('knowledge_base', 'База знаний')], max_length=32, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='editablepage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название школы'),
        ),
        migrations.AlterField(
            model_name='school',
            name='unique_code',
            field=models.CharField(blank=True, default=core.models.generate_unique_code, editable=False, max_length=32, unique=True, verbose_name='Уникальный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Супер-админ'), ('rayon_otdel', 'Районный отдел'), ('teacher', 'Учитель')], default='teacher', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat ID для уведомлений', max_length=64, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
