# Generated by Django 5.2.5 on 2025-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_editablepage_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablepage',
            name='page',
            field=models.CharField(choices=[('about', 'О проекте'), ('faq', 'Вопросы-ответы'), ('service_contacts', 'Контакты служб'), ('instructions', 'Инструкции'), ('knowledge_base', 'База знаний')], max_length=32, verbose_name='Страница'),
        ),
    ]
