# Generated by Django 5.2.5 on 2025-09-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_message_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='problem_type',
            field=models.CharField(choices=[('bullying', 'Буллинг'), ('extortion', 'Вымогательство'), ('violence', 'Насилие'), ('discrimination', 'Дискриминация'), ('academic', 'Академические проблемы'), ('other', 'Другое')], default='other', max_length=32),
        ),
    ]
